pdbbind_dir: "../../data/pdbbind/"
processed_pdbbind_dir: "../../data/processed_pdbbind/"
ligand_stats_file: "../../data/ligand_stats.yaml"
protein_config_file: "../../data/protein_config.yaml"
voxel_graph_dir: "../../data/graph_data/proteins/voxel_graphs/"
positive_voxel_graph_dir: "../../data/graph_data/voxel_positives/"
pocket_model_dir: "../../data/models/pocket_embed/"
corpus_dir: "../../data/graph_data/corpus/"
pocket_embeds_dir: "../../data/pocket_embeds/"
